# repos:
#   # General Python code quality hooks
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.2.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-yaml
#       - id: check-added-large-files

#   # Black code formatter
#   - repo: https://github.com/psf/black
#     rev: 24.3.0
#     hooks:
#       - id: black
#         language_version: python3

#   # isort: sort Python imports
#   - repo: https://github.com/pre-commit/mirrors-isort
#     rev: v5.10.1
#     hooks:
#       - id: isort
#         language_version: python3

#   # flake8: linting for Python
#   - repo: https://github.com/pycqa/flake8
#     rev: 6.1.0
#     hooks:
#       - id: flake8
#         additional_dependencies: [flake8-django]
#         args: ["--ignore=E501,F401"]
